/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.MotorPH.swingui;
import com.mycompany.MotorPH.EmployeeFileManager;
import com.mycompany.MotorPH.swingui.EmployeePanelSwing;
import com.mycompany.MotorPH.swingui.DashboardPanelSwing;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import org.pushingpixels.trident.Timeline;
/**
 *
 * @author adamm
 */
public class MotorPHAppSwing extends javax.swing.JFrame implements EmployeePanelListener {
    private EmployeePanelSwing empPanel;
    private PayrollPanelSwing payrollPanel;
    
    private EmployeeFileManager employeeFileManager = new EmployeeFileManager();
    CardLayout cl = new CardLayout();
    /**
     * Creates new form NewJFrame
     */
    public MotorPHAppSwing() {
        initComponents();
        initContentContainer();
        initFlatlafButtonStyle();
        
        setLocationRelativeTo(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MotorPHAppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MotorPHAppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MotorPHAppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MotorPHAppSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        MotorPHAppSwing motorPHApp = new MotorPHAppSwing();
        motorPHApp.toFront();
        motorPHApp.requestFocus();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        NavDrawer = new javax.swing.JLayeredPane();
        employeePageButton = new javax.swing.JButton();
        payrollPageButton = new javax.swing.JButton();
        dashboardPageButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        NavDrawer.setBackground(new java.awt.Color(30, 42, 86));
        NavDrawer.setForeground(new java.awt.Color(30, 42, 86));
        NavDrawer.setAlignmentX(0.0F);
        NavDrawer.setAlignmentY(0.0F);
        NavDrawer.setMinimumSize(new java.awt.Dimension(0, 600));
        NavDrawer.setName(""); // NOI18N
        NavDrawer.setOpaque(true);
        NavDrawer.setPreferredSize(new java.awt.Dimension(50, 600));
        NavDrawer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NavDrawerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NavDrawerMouseExited(evt);
            }
        });

        employeePageButton.setText("Employees");
        employeePageButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        employeePageButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        employeePageButton.setIconTextGap(15);
        employeePageButton.setMaximumSize(new java.awt.Dimension(200, 50));
        employeePageButton.setMinimumSize(new java.awt.Dimension(50, 50));
        employeePageButton.setPreferredSize(new java.awt.Dimension(200, 50));
        employeePageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeePageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeePageButtonMouseExited(evt);
            }
        });
        employeePageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeePageButton(evt);
            }
        });

        payrollPageButton.setText("Payroll");
        payrollPageButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        payrollPageButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        payrollPageButton.setIconTextGap(10);
        payrollPageButton.setMaximumSize(new java.awt.Dimension(200, 50));
        payrollPageButton.setMinimumSize(new java.awt.Dimension(50, 50));
        payrollPageButton.setPreferredSize(new java.awt.Dimension(200, 50));
        payrollPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payrollPageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payrollPageButtonMouseExited(evt);
            }
        });
        payrollPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollPageButton(evt);
            }
        });

        dashboardPageButton.setText("Dashboard");
        dashboardPageButton.setBorder(null);
        dashboardPageButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardPageButton.setMaximumSize(new java.awt.Dimension(200, 50));
        dashboardPageButton.setMinimumSize(new java.awt.Dimension(50, 50));
        dashboardPageButton.setOpaque(true);
        dashboardPageButton.setPreferredSize(new java.awt.Dimension(200, 50));
        dashboardPageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardPageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardPageButtonMouseExited(evt);
            }
        });
        dashboardPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardPageButtonemployeePageButton(evt);
            }
        });

        NavDrawer.setLayer(employeePageButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        NavDrawer.setLayer(payrollPageButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        NavDrawer.setLayer(dashboardPageButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout NavDrawerLayout = new javax.swing.GroupLayout(NavDrawer);
        NavDrawer.setLayout(NavDrawerLayout);
        NavDrawerLayout.setHorizontalGroup(
            NavDrawerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavDrawerLayout.createSequentialGroup()
                .addGroup(NavDrawerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dashboardPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NavDrawerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(employeePageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(payrollPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavDrawerLayout.setVerticalGroup(
            NavDrawerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavDrawerLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(dashboardPageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeePageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payrollPageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(220, 220, 220))
        );

        contentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(NavDrawer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(NavDrawer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NavDrawerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavDrawerMouseEntered
        navDrawerEntered();
    }//GEN-LAST:event_NavDrawerMouseEntered

    private void NavDrawerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NavDrawerMouseExited
        navDrawerExit();
    }//GEN-LAST:event_NavDrawerMouseExited

    private void employeePageButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeePageButton
        cl.show(contentPanel, "EmployeePage");
    }//GEN-LAST:event_employeePageButton

    private void payrollPageButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollPageButton
        cl.show(contentPanel, "PayrollPage");
    }//GEN-LAST:event_payrollPageButton

    private void employeePageButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeePageButtonMouseEntered
        navDrawerEntered();
        highlightNavButtonHover(employeePageButton);
    }//GEN-LAST:event_employeePageButtonMouseEntered

    private void employeePageButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeePageButtonMouseExited
        navDrawerExit();
        unhighlightNavButtonHover(employeePageButton);
    }//GEN-LAST:event_employeePageButtonMouseExited

    private void payrollPageButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollPageButtonMouseEntered
        navDrawerEntered();
        highlightNavButtonHover(payrollPageButton);
        
    }//GEN-LAST:event_payrollPageButtonMouseEntered

    private void payrollPageButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payrollPageButtonMouseExited
        navDrawerExit();
        unhighlightNavButtonHover(payrollPageButton);
    }//GEN-LAST:event_payrollPageButtonMouseExited

    private void dashboardPageButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPageButtonMouseEntered
        navDrawerEntered();
        highlightNavButtonHover(dashboardPageButton);
    }//GEN-LAST:event_dashboardPageButtonMouseEntered

    private void dashboardPageButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardPageButtonMouseExited
        navDrawerExit();
        unhighlightNavButtonHover(dashboardPageButton);
    }//GEN-LAST:event_dashboardPageButtonMouseExited

    private void dashboardPageButtonemployeePageButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardPageButtonemployeePageButton
        cl.show(contentPanel, "DashboardPage");
    }//GEN-LAST:event_dashboardPageButtonemployeePageButton
    
    
    private void navDrawerEntered(){
        NavDrawer.setPreferredSize(new Dimension(200, 600));
        getContentPane().revalidate();
    }
    
    private void navDrawerExit(){
        NavDrawer.setPreferredSize(new Dimension(50, 600)); // or desired width
        getContentPane().revalidate();
    }
    
    public void styleFlatLafButton(JButton button, String hexBackground, String hexForeground) {
        Color backgroundColor = Color.decode(hexBackground);
        Color foregroundColor = Color.decode(hexForeground);

        button.setBackground(backgroundColor);
        button.setForeground(foregroundColor);
        button.setOpaque(true);
        button.setContentAreaFilled(false);
    }
    
    public void initContentContainer(){
        empPanel = new EmployeePanelSwing(employeeFileManager);
        payrollPanel = new PayrollPanelSwing(employeeFileManager, empPanel);
        DashboardPanelSwing dasboardPanel = new DashboardPanelSwing();
        
        empPanel.setEmployeeDataListener(this);
        
        contentPanel.add(dasboardPanel, "DashboardPage");
        contentPanel.add(empPanel, "EmployeePage");
        contentPanel.add(payrollPanel, "PayrollPage");
        cl = (CardLayout)(contentPanel.getLayout());
    }
    
    public void initFlatlafButtonStyle(){
        styleFlatLafButton(dashboardPageButton, "#1E2A56", "#FFFFFF");
        styleFlatLafButton(employeePageButton, "#1E2A56", "#FFFFFF");
        styleFlatLafButton(payrollPageButton, "#1E2A56", "#FFFFFF");
        scaleButtonIcon(employeePageButton, "/icons/Employee.PNG");
        scaleButtonIcon(payrollPageButton, "/icons/Payroll.PNG");
        
    }
    
    public void scaleButtonIcon(JButton button, String resourcePath) {
        URL imgUrl = getClass().getResource(resourcePath);
        if (imgUrl != null) {
            ImageIcon originalIcon = new ImageIcon(imgUrl);
            Image scaledImage = originalIcon.getImage().getScaledInstance(40, 40, Image.SCALE_SMOOTH);
            button.setIcon(new ImageIcon(scaledImage));
        } else {
            System.err.println("Image not found: " + resourcePath);
        }
    }
    
    @Override
    public void onEmployeeDataSelected(String[] empData) {
        payrollPanel.setTextfieldsData(empData);
        
        cl.show(contentPanel, "PayrollPage");
    }

    
    public void highlightNavButtonHover(JButton button) {
        styleFlatLafButton(button, "#3D4F8C", "#FFFFFF");
    }
    public void unhighlightNavButtonHover(JButton button) {
        styleFlatLafButton(button, "#1E2A56", "#FFFFFF");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane NavDrawer;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton dashboardPageButton;
    private javax.swing.JButton employeePageButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JButton payrollPageButton;
    // End of variables declaration//GEN-END:variables
}
