/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.MotorPH.swingui;

import java.awt.Image;
import javax.swing.ImageIcon;
import com.formdev.flatlaf.FlatLightLaf;
import com.mycompany.MotorPH.EmployeeFileManager;
import com.mycompany.MotorPH.Grosswage;
import com.mycompany.MotorPH.Netwage;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author adamm
 */
public class PayrollPanelSwing extends javax.swing.JPanel {
    private Grosswage grosswage = new Grosswage();
    private Netwage netwage = new Netwage();
    
    private boolean editableState = false;
    private EmployeeFileManager employeeFileManager;
    private EmployeePanelSwing employeePanel;
    
    public String[] employeeData;
        
    /**
     * Creates new form PayrollPanel
     */
    public PayrollPanelSwing(EmployeeFileManager employeeFileManager, EmployeePanelSwing employeePanel) {try {
        this.employeeFileManager = employeeFileManager;
        this.employeePanel = employeePanel;
        
        javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
            } catch (Exception ex) {
              System.err.println("Failed to initialize LaF");
            }
    
        initComponents();
        profileImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        grossHourlyField = new javax.swing.JTextField();
        grossTotalHoursField = new javax.swing.JTextField();
        grossWageField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        netSSSField = new javax.swing.JTextField();
        netPhilhealthField = new javax.swing.JTextField();
        netPagibigField = new javax.swing.JTextField();
        netTotalDeductionsField = new javax.swing.JTextField();
        netLateField = new javax.swing.JTextField();
        netTotalHoursField = new javax.swing.JTextField();
        netGrossField = new javax.swing.JTextField();
        netTaxableField = new javax.swing.JTextField();
        netWithholdingTaxField = new javax.swing.JTextField();
        netWageField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        imageView = new javax.swing.JLabel();
        empNameField = new javax.swing.JTextField();
        monthField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        empIDField = new javax.swing.JTextField();
        empPositionField = new javax.swing.JTextField();
        empStatusField = new javax.swing.JTextField();
        empBirthdayField = new javax.swing.JTextField();
        empPhoneNumberField = new javax.swing.JTextField();
        empAddressField = new javax.swing.JTextField();
        empSupervisorField = new javax.swing.JTextField();
        empSSSField = new javax.swing.JTextField();
        empPhilhealthField = new javax.swing.JTextField();
        empTinField = new javax.swing.JTextField();
        empPagibigField = new javax.swing.JTextField();
        empBasicSalaryField1 = new javax.swing.JTextField();
        empRiceSubsidyField = new javax.swing.JTextField();
        empPhoneAllowanceField = new javax.swing.JTextField();
        empClothingAllowanceField1 = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        empGrossSemiField = new javax.swing.JTextField();
        empGrossHourlyRateField = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        grossHourlyField.setBackground(new java.awt.Color(242, 242, 242));
        grossHourlyField.setEnabled(false);

        grossTotalHoursField.setEnabled(false);

        grossWageField.setEnabled(false);

        jLabel1.setText("Hourly Rate:");

        jLabel2.setText("Total Hours:");

        jLabel3.setText("Gross wage:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(grossWageField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grossTotalHoursField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grossHourlyField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(566, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grossHourlyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grossTotalHoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grossWageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gross wage", jPanel1);

        netSSSField.setBackground(new java.awt.Color(242, 242, 242));
        netSSSField.setToolTipText("");
        netSSSField.setEnabled(false);

        netPhilhealthField.setBackground(new java.awt.Color(242, 242, 242));
        netPhilhealthField.setToolTipText("");
        netPhilhealthField.setEnabled(false);

        netPagibigField.setBackground(new java.awt.Color(242, 242, 242));
        netPagibigField.setToolTipText("");
        netPagibigField.setEnabled(false);

        netTotalDeductionsField.setBackground(new java.awt.Color(242, 242, 242));
        netTotalDeductionsField.setToolTipText("");
        netTotalDeductionsField.setEnabled(false);

        netLateField.setBackground(new java.awt.Color(242, 242, 242));
        netLateField.setToolTipText("");
        netLateField.setEnabled(false);

        netTotalHoursField.setBackground(new java.awt.Color(242, 242, 242));
        netTotalHoursField.setToolTipText("");
        netTotalHoursField.setEnabled(false);

        netGrossField.setBackground(new java.awt.Color(242, 242, 242));
        netGrossField.setToolTipText("");
        netGrossField.setEnabled(false);

        netTaxableField.setBackground(new java.awt.Color(242, 242, 242));
        netTaxableField.setToolTipText("");
        netTaxableField.setEnabled(false);

        netWithholdingTaxField.setBackground(new java.awt.Color(242, 242, 242));
        netWithholdingTaxField.setToolTipText("");
        netWithholdingTaxField.setEnabled(false);

        netWageField.setBackground(new java.awt.Color(242, 242, 242));
        netWageField.setToolTipText("");
        netWageField.setEnabled(false);

        jLabel4.setText("SSS");

        jLabel5.setText("Philhealth");

        jLabel6.setText("Pagibig");

        jLabel7.setText("Late");

        jLabel8.setText("Total Deductions");

        jLabel9.setText("Total Hours");

        jLabel10.setText("Gross Wage");

        jLabel11.setText("Taxable Income");

        jLabel12.setText("Withholding Tax");

        jLabel13.setText("Net Wage");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(netTotalDeductionsField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netLateField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netPagibigField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netPhilhealthField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netSSSField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(netWageField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netWithholdingTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netTaxableField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netGrossField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netTotalHoursField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(netTotalHoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(netSSSField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(netPhilhealthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(netGrossField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addGap(3, 3, 3)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(netTaxableField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(netPagibigField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(netLateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netWithholdingTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(netTotalDeductionsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netWageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Net wage", jPanel2);

        imageView.setPreferredSize(new java.awt.Dimension(150, 150));

        empNameField.setEnabled(false);

        monthField.setToolTipText("");
        monthField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthFieldFocusLost(evt);
            }
        });

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        empIDField.setEditable(false);

        empPositionField.setEnabled(false);

        empStatusField.setEnabled(false);

        empBirthdayField.setEnabled(false);

        empPhoneNumberField.setEnabled(false);

        empAddressField.setEnabled(false);

        empSupervisorField.setEnabled(false);

        empSSSField.setEnabled(false);

        empPhilhealthField.setEnabled(false);

        empTinField.setEnabled(false);

        empPagibigField.setEnabled(false);

        empBasicSalaryField1.setEnabled(false);

        empRiceSubsidyField.setEnabled(false);

        empPhoneAllowanceField.setEnabled(false);

        empClothingAllowanceField1.setEnabled(false);

        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.setEnabled(false);
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        empGrossSemiField.setEnabled(false);

        empGrossHourlyRateField.setEnabled(false);

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(imageView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empGrossSemiField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(updateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calculateButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(empGrossHourlyRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(empIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(empBirthdayField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(empSSSField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(empBasicSalaryField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(empNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(empAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(empPhilhealthField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(empRiceSubsidyField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(empPositionField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(empPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(empTinField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(empPhoneAllowanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(empStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(empSupervisorField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(empPagibigField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(empClothingAllowanceField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empBirthdayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empSSSField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empBasicSalaryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empPhilhealthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empRiceSubsidyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empPositionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empTinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empPhoneAllowanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empStatusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empSupervisorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empPagibigField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empClothingAllowanceField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empGrossSemiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empGrossHourlyRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Delete)
                    .addComponent(updateButton)
                    .addComponent(editButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // CALCULATE GROSS OR NET WAGE DEPENDING ON WHICH TAB IS OPEN
    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        String empID = empIDField.getText();
        String monthText = monthField.getText();

        Integer month = inputValidation(empID, monthText);      

        switch (jTabbedPane1.getSelectedIndex()) {
            case 0:
                grosswage.calculate(empID, month);
                printGross();
                break;
            case 1:
                netwage.calculate(empID, month);
                printNet();
                break;
            default:
                System.out.println("No action for this tab");
        }
    }//GEN-LAST:event_calculateButtonActionPerformed
    
    // TEXT PLACEHOLDER LOGIC 
    private void monthFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthFieldFocusLost
        if (monthField.getText().isEmpty()){
            monthField.setForeground(Color.GRAY);
            monthField.setText("Enter Month...");
        }
    }//GEN-LAST:event_monthFieldFocusLost
    
    // TEXT PLACEHOLDER LOGIC
    private void monthFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthFieldFocusGained
        if (monthField.getText().equals("Enter Month...")){
            monthField.setForeground(Color.BLACK);
            monthField.setText("");
        }
    }//GEN-LAST:event_monthFieldFocusGained

    // DELETES RECORD FROM TABLE, CACHE AND CSV FILE
    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        int response = JOptionPane.showConfirmDialog(
        null,
        "Are you sure you want to delete this record?",
        "Confirm Deletion",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            employeeFileManager.deleteRecord(employeeData[0]);
            employeePanel.refreshEmployeeTable();
            JOptionPane.showMessageDialog(null, "Record successfully deleted.");
        } else {
            // Optional: notify user cancelation
            JOptionPane.showMessageDialog(null, "Deletion canceled.");
        }
    }//GEN-LAST:event_DeleteActionPerformed
    
    // UPDATES RECORD ON TABLE, CACHE AND CSV FILE
    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
           
        int response = JOptionPane.showConfirmDialog(
        null,
        "Are you sure you want to update this record?",
        "Confirm Update",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.WARNING_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            employeeFileManager.updateRecord(updateData());
            employeePanel.refreshEmployeeTable();
            editableState = !editableState;
            toggleEmployeeDataFields(editableState);
            updateButton.setEnabled(editableState);
            JOptionPane.showMessageDialog(null, "Record successfully updated.");
        } else {
            // Optional: notify user cancelation
            JOptionPane.showMessageDialog(null, "Update canceled.");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    // TOGGLE FOR TEXTFIELDS FOR EDITING
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        editableState = !editableState;                // Toggle editable state
        toggleEmployeeDataFields(editableState);       // Enable or disable fields

        // Reset fields with existing data only if not null
        if (employeeData != null) {
            setTextfieldsData(employeeData);
        }
    }//GEN-LAST:event_editButtonActionPerformed
    
    // PRINTS GROSS WAGE
    public void printGross(){
        empNameField.setText(grosswage.getEmployeeName());
        grossHourlyField.setText(String.format("%.2f", grosswage.getHourly()));
        grossTotalHoursField.setText(String.format("%.0f", grosswage.getHours()));
        grossWageField.setText(String.format("%.2f", grosswage.getGross()));
    }
    
    // PRINGS NET WAGE
    private void printNet(){
        empNameField.setText(netwage.getEmpName());
        netSSSField.setText(String.format("%.2f", netwage.getSssData()));
        netPhilhealthField.setText(String.format("%.2f", netwage.getPhilhealthData()));
        netPagibigField.setText(String.format("%.2f", netwage.getPagibigData()));
        netLateField.setText(String.format("%.2f", netwage.getLateData()));
        netTotalDeductionsField.setText(String.format("%.2f", netwage.getTotalDeduction()));
        netTotalHoursField.setText(String.format("%.2f", grosswage.getHours()));
        netGrossField.setText(String.format("%.2f", grosswage.getGross()));
        netTaxableField.setText(String.format("%.2f", netwage.getTaxableIncome()));
        netWithholdingTaxField.setText(String.format("%.2f", netwage.getTax()));
        netWageField.setText(String.format("%.2f", netwage.getNet()));
    }
    
    // SETS DATA UPON EMPLOYEE VIEW
    public void setTextfieldsData(String[] data) {
        empIDField.setText(data[0]);
        empNameField.setText(data[1] + ", " + data[2]);
        empPositionField.setText(data[11]);
        empStatusField.setText(data[10]);

        empBirthdayField.setText(data[3]);
        empAddressField.setText(data[4]);
        empPhoneNumberField.setText(data[5]);
        empSupervisorField.setText(data[12]);

        empSSSField.setText(data[6]);
        empPhilhealthField.setText(data[7]);
        empTinField.setText(data[8]);
        empPagibigField.setText(data[9]);

        empBasicSalaryField1.setText(data[13]);
        empRiceSubsidyField.setText(data[14]);
        empPhoneAllowanceField.setText(data[15]);
        empClothingAllowanceField1.setText(data[16]);
        
        empGrossSemiField.setText(data[17]);
        empGrossHourlyRateField.setText(data[18]);
        
        employeeData = data;
    }
    
    public String[] updateData(){
        String[] updatedData = new String[] {
            empIDField.getText().trim(),
            empNameField.getText().split(",")[0].trim(), // Last Name
            empNameField.getText().split(",")[1].trim(), // First Name
            empBirthdayField.getText().trim(),
            empAddressField.getText().trim(),
            empPhoneNumberField.getText().trim(),
            empSSSField.getText().trim(),
            empPhilhealthField.getText().trim(),
            empTinField.getText().trim(),
            empPagibigField.getText().trim(),
            empStatusField.getText().trim(),
            empPositionField.getText().trim(),
            empSupervisorField.getText().trim(),
            empBasicSalaryField1.getText().trim(),
            empRiceSubsidyField.getText().trim(),
            empPhoneAllowanceField.getText().trim(),
            empClothingAllowanceField1.getText().trim(),
            empGrossSemiField.getText().trim(),
            empGrossHourlyRateField.getText().trim()
        };
        return updatedData;
    }
    
    // LOGIC FOR TEXTFILED TOGGLING
    private void toggleEmployeeDataFields(boolean state) {
        empIDField.setEnabled(state);
        empNameField.setEnabled(state);
        empPositionField.setEnabled(state);
        empStatusField.setEnabled(state);
        empBirthdayField.setEnabled(state);
        empAddressField.setEnabled(state);
        empPhoneNumberField.setEnabled(state);
        empSupervisorField.setEnabled(state);
        empSSSField.setEnabled(state);
        empPhilhealthField.setEnabled(state);
        empTinField.setEnabled(state);
        empPagibigField.setEnabled(state);
        empBasicSalaryField1.setEnabled(state);
        empRiceSubsidyField.setEnabled(state);
        empPhoneAllowanceField.setEnabled(state);
        empClothingAllowanceField1.setEnabled(state);
        empGrossSemiField.setEnabled(state);
        empGrossHourlyRateField.setEnabled(state);
        
        updateButton.setEnabled(state);
    }
    
    // LOADS EMPLOYEE PROFILE IMAGE IF ANY
    private void profileImage() {
        java.net.URL imgURL = getClass().getResource("/icons/Employee.PNG");
            if (imgURL != null) {
                ImageIcon originalIcon = new ImageIcon(imgURL);
                Image scaledImage = originalIcon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                imageView.setIcon(new ImageIcon(scaledImage));
            } else {
                System.err.println("Couldn't find file: /icons/Employee.PNG");
            }
    }
    
    // VALIDATES INPUT FOR CALCULATION, ID AND MONTH ARE BOTH REQUIRED
    private Integer inputValidation(String empID, String monthText) {
    // Check if Employee ID is missing
    if (empID == null || empID.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Employee ID is required", "Missing input", JOptionPane.ERROR_MESSAGE);
        return null;
    }

    // Check if Employee ID is numeric
    try {
        Integer.parseInt(empID);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Employee ID must be numeric", "Invalid input", JOptionPane.ERROR_MESSAGE);
        return null;
    }

    // Validate Month
    try {
        int month = Integer.parseInt(monthText);
        if (month < 1 || month > 12) {
            JOptionPane.showMessageDialog(null, "Months must be 1-12", "Invalid input", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        return month;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Months must be numeric", "Invalid input", JOptionPane.ERROR_MESSAGE);
        return null;
    }
}
   
    // FOR ALERT REUSABILITY
    private void showAlert(int messageType, String title, String message) {
        JOptionPane.showMessageDialog(null, message, title, messageType);
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calculateButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField empAddressField;
    private javax.swing.JTextField empBasicSalaryField1;
    private javax.swing.JTextField empBirthdayField;
    private javax.swing.JTextField empClothingAllowanceField1;
    private javax.swing.JTextField empGrossHourlyRateField;
    private javax.swing.JTextField empGrossSemiField;
    private javax.swing.JTextField empIDField;
    private javax.swing.JTextField empNameField;
    private javax.swing.JTextField empPagibigField;
    private javax.swing.JTextField empPhilhealthField;
    private javax.swing.JTextField empPhoneAllowanceField;
    private javax.swing.JTextField empPhoneNumberField;
    private javax.swing.JTextField empPositionField;
    private javax.swing.JTextField empRiceSubsidyField;
    private javax.swing.JTextField empSSSField;
    private javax.swing.JTextField empStatusField;
    private javax.swing.JTextField empSupervisorField;
    private javax.swing.JTextField empTinField;
    private javax.swing.JTextField grossHourlyField;
    private javax.swing.JTextField grossTotalHoursField;
    private javax.swing.JTextField grossWageField;
    private javax.swing.JLabel imageView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField monthField;
    private javax.swing.JTextField netGrossField;
    private javax.swing.JTextField netLateField;
    private javax.swing.JTextField netPagibigField;
    private javax.swing.JTextField netPhilhealthField;
    private javax.swing.JTextField netSSSField;
    private javax.swing.JTextField netTaxableField;
    private javax.swing.JTextField netTotalDeductionsField;
    private javax.swing.JTextField netTotalHoursField;
    private javax.swing.JTextField netWageField;
    private javax.swing.JTextField netWithholdingTaxField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
