/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.MotorPH;

import java.awt.Image;
import javax.swing.ImageIcon;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javafx.scene.control.Alert;
import javax.swing.JOptionPane;

/**
 *
 * @author adamm
 */
public class PayrollPanelSwing extends javax.swing.JPanel {
    private Grosswage grosswage = new Grosswage();
    private Netwage netwage = new Netwage();
    /**
     * Creates new form PayrollPanel
     */
    public PayrollPanelSwing() {try {
        javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
            } catch (Exception ex) {
              System.err.println("Failed to initialize LaF");
            }
    
        initComponents();
        profileImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        grossHourlyField = new javax.swing.JTextField();
        grossTotalHoursField = new javax.swing.JTextField();
        grossWageField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        netSSSField = new javax.swing.JTextField();
        netPhilhealthField = new javax.swing.JTextField();
        netPagibigField = new javax.swing.JTextField();
        netTotalDeductionsField = new javax.swing.JTextField();
        netLateField = new javax.swing.JTextField();
        netTotalHoursField = new javax.swing.JTextField();
        netGrossField = new javax.swing.JTextField();
        netTaxableField = new javax.swing.JTextField();
        netWithholdingTaxField = new javax.swing.JTextField();
        netWageField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        imageView = new javax.swing.JLabel();
        empNameField = new javax.swing.JTextField();
        monthField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        empIDField = new javax.swing.JTextField();

        jPasswordField1.setText("jPasswordField1");

        grossHourlyField.setEnabled(false);

        grossTotalHoursField.setEnabled(false);

        grossWageField.setEnabled(false);

        jLabel1.setText("Hourly Rate:");

        jLabel2.setText("Total Hours:");

        jLabel3.setText("Gross wage:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(grossWageField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grossTotalHoursField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grossHourlyField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(566, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grossHourlyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grossTotalHoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grossWageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gross wage", jPanel1);

        netSSSField.setToolTipText("");
        netSSSField.setEnabled(false);

        netPhilhealthField.setToolTipText("");
        netPhilhealthField.setEnabled(false);

        netPagibigField.setToolTipText("");
        netPagibigField.setEnabled(false);

        netTotalDeductionsField.setToolTipText("");
        netTotalDeductionsField.setEnabled(false);

        netLateField.setToolTipText("");
        netLateField.setEnabled(false);

        netTotalHoursField.setToolTipText("");
        netTotalHoursField.setEnabled(false);

        netGrossField.setToolTipText("");
        netGrossField.setEnabled(false);

        netTaxableField.setToolTipText("");
        netTaxableField.setEnabled(false);

        netWithholdingTaxField.setToolTipText("");
        netWithholdingTaxField.setEnabled(false);

        netWageField.setToolTipText("");
        netWageField.setEnabled(false);

        jLabel4.setText("SSS");

        jLabel5.setText("Philhealth");

        jLabel6.setText("Pagibig");

        jLabel7.setText("Late");

        jLabel8.setText("Total Deductions");

        jLabel9.setText("Total Hours");

        jLabel10.setText("Gross Wage");

        jLabel11.setText("Taxable Income");

        jLabel12.setText("Withholding Tax");

        jLabel13.setText("Net Wage");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(netTotalDeductionsField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netLateField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netPagibigField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netPhilhealthField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netSSSField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(netWageField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netWithholdingTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netTaxableField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netGrossField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(netTotalHoursField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(108, 108, 108))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(netTotalHoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(netGrossField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(netTaxableField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(netSSSField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(netPhilhealthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(netPagibigField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(netLateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netWithholdingTaxField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(netTotalDeductionsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(netWageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addGap(39, 39, 39))))
        );

        jTabbedPane1.addTab("Net wage", jPanel2);

        imageView.setPreferredSize(new java.awt.Dimension(150, 150));

        empNameField.setEnabled(false);

        monthField.setForeground(new java.awt.Color(204, 204, 204));
        monthField.setText("Enter Month...");
        monthField.setToolTipText("");
        monthField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                monthFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                monthFieldFocusLost(evt);
            }
        });

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        empIDField.setForeground(new java.awt.Color(204, 204, 204));
        empIDField.setText("Enter Employee ID...");
        empIDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                empIDFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                empIDFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(imageView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calculateButton)
                .addGap(18, 18, 18)
                .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(empNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(empIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateButton)
                    .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
    String empID = empIDField.getText();
    String monthText = monthField.getText();
    
    Integer month = inputValidation(empID, monthText);      
           
    switch (jTabbedPane1.getSelectedIndex()) {
        case 0:
            grosswage.calculate(empID, month);
            printGross();
            break;
        case 1:
            netwage.calculate(empID, month);
            printNet();
            break;
        default:
            System.out.println("No action for this tab");
    }
    

    }//GEN-LAST:event_calculateButtonActionPerformed

    private void empIDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empIDFieldFocusLost
        if (empIDField.getText().isEmpty()){
            empIDField.setForeground(Color.GRAY);
            empIDField.setText("Enter Employee ID...");
        }
    }//GEN-LAST:event_empIDFieldFocusLost

    private void empIDFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empIDFieldFocusGained
        if (empIDField.getText().equals("Enter Employee ID...")){
            empIDField.setForeground(Color.BLACK);
            empIDField.setText("");
        }
    }//GEN-LAST:event_empIDFieldFocusGained

    private void monthFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthFieldFocusLost
        if (monthField.getText().isEmpty()){
            monthField.setForeground(Color.GRAY);
            monthField.setText("Enter Month...");
        }
    }//GEN-LAST:event_monthFieldFocusLost

    private void monthFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_monthFieldFocusGained
        if (monthField.getText().equals("Enter Month...")){
            monthField.setForeground(Color.BLACK);
            monthField.setText("");
        }
    }//GEN-LAST:event_monthFieldFocusGained
    
    public void printGross(){
        empNameField.setText(grosswage.getEmployeeName());
        grossHourlyField.setText(String.format("%.2f", grosswage.getHourly()));
        grossTotalHoursField.setText(String.format("%.0f", grosswage.getHours()));
        grossWageField.setText(String.format("%.2f", grosswage.getGross()));
    }
    
    private void printNet(){
        empNameField.setText(netwage.getEmpName());
        netSSSField.setText(String.format("%.2f", netwage.getSssData()));
        netPhilhealthField.setText(String.format("%.2f", netwage.getPhilhealthData()));
        netPagibigField.setText(String.format("%.2f", netwage.getPagibigData()));
        netLateField.setText(String.format("%.2f", netwage.getLateData()));
        netTotalDeductionsField.setText(String.format("%.2f", netwage.getTotalDeduction()));
        netTotalHoursField.setText(String.format("%.2f", grosswage.getHours()));
        netGrossField.setText(String.format("%.2f", grosswage.getGross()));
        netTaxableField.setText(String.format("%.2f", netwage.getTaxableIncome()));
        netWithholdingTaxField.setText(String.format("%.2f", netwage.getTax()));
        netWageField.setText(String.format("%.2f", netwage.getNet()));
    }
    
    public void profileImage() {
        java.net.URL imgURL = getClass().getResource("/icons/Employee.PNG");
            if (imgURL != null) {
                ImageIcon originalIcon = new ImageIcon(imgURL);
                Image scaledImage = originalIcon.getImage().getScaledInstance(150, 150, Image.SCALE_SMOOTH);
                imageView.setIcon(new ImageIcon(scaledImage));
            } else {
                System.err.println("Couldn't find file: /icons/Employee.PNG");
            }
    }
    
    private Integer inputValidation(String empID, String monthText) {
    // Check if Employee ID is missing
    if (empID == null || empID.trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Employee ID is required", "Missing input", JOptionPane.ERROR_MESSAGE);
        return null;
    }

    // Check if Employee ID is numeric
    try {
        Integer.parseInt(empID);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Employee ID must be numeric", "Invalid input", JOptionPane.ERROR_MESSAGE);
        return null;
    }

    // Validate Month
    try {
        int month = Integer.parseInt(monthText);
        if (month < 1 || month > 12) {
            JOptionPane.showMessageDialog(null, "Months must be 1-12", "Invalid input", JOptionPane.ERROR_MESSAGE);
            return null;
        }
        return month;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Months must be numeric", "Invalid input", JOptionPane.ERROR_MESSAGE);
        return null;
    }
}
    
    private void showAlert(int messageType, String title, String message) {
        JOptionPane.showMessageDialog(null, message, title, messageType);
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JTextField empIDField;
    private javax.swing.JTextField empNameField;
    private javax.swing.JTextField grossHourlyField;
    private javax.swing.JTextField grossTotalHoursField;
    private javax.swing.JTextField grossWageField;
    private javax.swing.JLabel imageView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField monthField;
    private javax.swing.JTextField netGrossField;
    private javax.swing.JTextField netLateField;
    private javax.swing.JTextField netPagibigField;
    private javax.swing.JTextField netPhilhealthField;
    private javax.swing.JTextField netSSSField;
    private javax.swing.JTextField netTaxableField;
    private javax.swing.JTextField netTotalDeductionsField;
    private javax.swing.JTextField netTotalHoursField;
    private javax.swing.JTextField netWageField;
    private javax.swing.JTextField netWithholdingTaxField;
    // End of variables declaration//GEN-END:variables
}
